"use client";
import { createFileRoute } from "@/lib/next-router-compat";
import { useAdminLoyaltyLedger, useAdminLoyaltySummary, type AdminLedger } from "@/lib/loyalty-api";
import { PageHeader } from "@/components/admin/PageHeader";
import { DataTable, type Column } from "@/components/admin/DataTable";
import { StatCard } from "@/components/admin/StatCard";
import { EmptyState, LoadingSkeleton } from "@/components/admin/EmptyState";
import { Button } from "@/components/ui/button";
import { Gift, RefreshCw, Sparkles, Users, Wallet } from "lucide-react";
export const Route=createFileRoute("/loyalty")({head:()=>({meta:[{title:"Loyalty & Referrals — Fresh15 Admin"},{name:"description",content:"Monitor FreshPoints issuance, redemption and referral performance."}]}),component:LoyaltyAdminPage});
const userOf=(r:AdminLedger)=>typeof r.userId==="object"&&r.userId?r.userId:null;
function LoyaltyAdminPage(){ const summary=useAdminLoyaltySummary(); const ledger=useAdminLoyaltyLedger(); const columns:Column<AdminLedger>[]=[{key:"customer",header:"Customer",render:r=>{const u=userOf(r);return <div><div className="text-sm font-semibold">{u?.name??"Customer"}</div><div className="text-xs text-muted-foreground">{u?.email??"—"}</div></div>}},{key:"activity",header:"Activity",render:r=><div><div className="text-sm font-medium">{r.description||r.type.replaceAll("_"," ")}</div><div className="text-xs text-muted-foreground">{new Date(r.createdAt).toLocaleString("en-IN")}</div></div>},{key:"points",header:"Points",render:r=><span className={"font-bold "+(r.points>=0?"text-emerald-600":"")}>{r.points>=0?"+":""}{r.points}</span>},{key:"balance",header:"Balance",render:r=>r.balanceAfter.toLocaleString("en-IN")}]; return <div className="space-y-6"><PageHeader title="Loyalty & Referrals" description="Track FreshPoints economics and successful customer referrals." actions={<Button variant="outline" size="sm" onClick={()=>{void summary.refetch();void ledger.refetch();}}><RefreshCw className="h-4 w-4"/>Refresh</Button>}/>{summary.isLoading?<LoadingSkeleton rows={2}/>:<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><StatCard label="Loyalty wallets" value={String(summary.data?.wallets??0)} icon={Wallet}/><StatCard label="Points issued" value={(summary.data?.pointsIssued??0).toLocaleString("en-IN")} icon={Sparkles} tone="success"/><StatCard label="Points redeemed" value={(summary.data?.pointsRedeemed??0).toLocaleString("en-IN")} icon={Gift} tone="warning"/><StatCard label="Successful referrals" value={String(summary.data?.successfulReferrals??0)} icon={Users}/></div>}{summary.data?.topWallets?.length?<div className="rounded-2xl border bg-card p-4"><div className="mb-3 text-sm font-semibold">Top FreshPoints customers</div><div className="grid gap-2 md:grid-cols-2">{summary.data.topWallets.slice(0,6).map(w=>{const u=typeof w.userId==="object"&&w.userId?w.userId:null;return <div key={w._id} className="flex items-center justify-between rounded-xl border p-3"><div><div className="text-sm font-semibold">{u?.name??"Customer"}</div><div className="text-xs text-muted-foreground">{u?.email??w.referralCode}</div></div><div className="text-right"><div className="font-black">{w.balance}</div><div className="text-[10px] text-muted-foreground">points</div></div></div>})}</div></div>:null}{ledger.isLoading?<LoadingSkeleton rows={8}/>:ledger.isError?<EmptyState title="Couldn’t load loyalty ledger" description={ledger.error instanceof Error?ledger.error.message:"Please try again."}/>:<DataTable data={ledger.data??[]} columns={columns} pageSize={12} rowId={r=>r._id} searchable={r=>`${userOf(r)?.name??""} ${userOf(r)?.email??""} ${r.type} ${r.description??""}`} emptyTitle="No loyalty activity yet" emptyDescription="FreshPoints activity will appear after delivered orders and referrals."/>}</div> }
